#!/usr/bin/env python3
"""Shared scan targets and safety classification for mac-cleaner."""

from __future__ import annotations

import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path

HOME = Path.home()
MIN_SCAN_SIZE = 1024 * 1024
MIN_SYSTEM_DATA_SIZE = 100 * 1024 * 1024
PROTECTED_CACHE_DIRS = {"ms-playwright", "ms-playwright-go"}
PROTECTED_DEVELOPMENT_STORE_DIR_NAMES = {".pub-cache"}


@dataclass(frozen=True)
class Target:
    name: str
    path: Path
    category: str
    group: str
    safety: str
    cleanable: bool
    reason: str


def fmt_size(size_bytes: int) -> str:
    if size_bytes < 1024:
        return f"{size_bytes} B"
    if size_bytes < 1024 ** 2:
        return f"{size_bytes / 1024:.1f} KB"
    if size_bytes < 1024 ** 3:
        return f"{size_bytes / 1024**2:.1f} MB"
    return f"{size_bytes / 1024**3:.2f} GB"


def dir_size(path: Path) -> int:
    total = 0
    try:
        if path.is_file() or path.is_symlink():
            return disk_usage(path)
        for entry in path.rglob("*"):
            try:
                if entry.is_file() and not entry.is_symlink():
                    total += disk_usage(entry)
            except (PermissionError, OSError):
                pass
    except (PermissionError, OSError):
        pass
    return total


def disk_usage(path: Path) -> int:
    stat = path.stat()
    blocks = getattr(stat, "st_blocks", 0)
    if blocks:
        return blocks * 512
    return stat.st_size


def known_targets(home: Path = HOME) -> list[Target]:
    safe = "safe-cache"
    review = "review-required"
    blocked = "never-default-delete"
    return [
        Target("App caches", home / "Library/Caches", "cache", "System & App Caches", safe, True, "Regenerated by apps; protected cache subdirectories are skipped."),
        Target("User logs", home / "Library/Logs", "logs", "System Logs", review, True, "Logs can be removed but may hide recurring crash symptoms."),
        Target("System logs", Path("/private/var/log"), "logs", "System Logs", review, True, "System logs are review-required and may need permissions."),
        Target("Chrome cache", home / "Library/Caches/Google/Chrome/Default/Cache", "browser", "Browser Caches", safe, True, "Browser cache can be regenerated."),
        Target("Chrome app cache", home / "Library/Caches/com.google.Chrome", "browser", "Browser Caches", safe, True, "Browser cache can be regenerated."),
        Target("Firefox cache", home / "Library/Caches/Firefox", "browser", "Browser Caches", safe, True, "Browser cache can be regenerated."),
        Target("Safari cache", home / "Library/Caches/com.apple.Safari", "browser", "Browser Caches", safe, True, "Browser cache can be regenerated."),
        Target("Edge cache", home / "Library/Caches/com.microsoft.edgemac", "browser", "Browser Caches", safe, True, "Browser cache can be regenerated."),
        Target("npm cache", home / ".npm/_cacache", "dev", "Development - Node.js", safe, True, "Package cache can be rebuilt by npm."),
        Target("Yarn cache", home / ".yarn/cache", "dev", "Development - Node.js", safe, True, "Package cache can be rebuilt by Yarn."),
        Target("pnpm store", home / ".pnpm-store", "dev", "Development - Node.js", review, True, "Package store can be large; projects may redownload packages."),
        Target("pip cache", home / ".cache/pip", "dev", "Development - Python", safe, True, "Package cache can be rebuilt by pip."),
        Target("pip cache (macOS)", home / "Library/Caches/pip", "dev", "Development - Python", safe, True, "Package cache can be rebuilt by pip."),
        Target("Conda packages cache", home / ".conda/pkgs", "dev", "Development - Python", review, True, "Conda package cache can be large and redownloadable."),
        Target("Homebrew cache", Path("/opt/homebrew/Caches"), "dev", "Development - Homebrew", safe, True, "Homebrew cache can be rebuilt."),
        Target("Homebrew cache", home / "Library/Caches/Homebrew", "dev", "Development - Homebrew", safe, True, "Homebrew cache can be rebuilt."),
        Target("Xcode DerivedData", home / "Library/Developer/Xcode/DerivedData", "xcode", "Development - Xcode", safe, True, "Generated build output; Xcode will rebuild it."),
        Target("Xcode Archives", home / "Library/Developer/Xcode/Archives", "xcode", "Development - Xcode", review, True, "May contain app archives worth keeping."),
        Target("Xcode iOS Device Support", home / "Library/Developer/Xcode/iOS DeviceSupport", "xcode", "Development - Xcode", review, True, "Old device symbols can be removed if not needed."),
        Target("Simulator caches", home / "Library/Developer/CoreSimulator/Caches", "xcode", "Development - Xcode", safe, True, "Simulator cache can be regenerated."),
        Target("CocoaPods cache", home / "Library/Caches/CocoaPods", "dev", "Development - CocoaPods", safe, True, "Package cache can be rebuilt."),
        Target("Gradle caches", home / ".gradle/caches", "dev", "Development - Gradle/Java", review, True, "Gradle can rebuild caches; active builds may redownload."),
        Target("Gradle wrapper distributions", home / ".gradle/wrapper/dists", "dev", "Development - Gradle/Java", review, True, "Gradle wrappers can be redownloaded."),
        Target("Dart pub cache", home / ".pub-cache", "dev", "Development - Flutter/Dart", blocked, False, "Shared Dart/Flutter package store; use dart/flutter pub cache commands after closing active Flutter work."),
        Target("Flutter engine cache", home / "Library/Caches/flutter_engine", "dev", "Development - Flutter/Dart", safe, True, "Flutter cache can be regenerated."),
        Target("VS Code cache", home / "Library/Application Support/Code/Cache", "ide", "IDE - VS Code", safe, True, "Editor cache only; do not close editor automatically."),
        Target("VS Code cached data", home / "Library/Application Support/Code/CachedData", "ide", "IDE - VS Code", safe, True, "Editor cache only; do not close editor automatically."),
        Target("VS Code cached extensions", home / "Library/Application Support/Code/CachedExtensions", "ide", "IDE - VS Code", safe, True, "Cached extension payloads can be redownloaded."),
        Target("VS Code cached VSIXs", home / "Library/Application Support/Code/CachedExtensionVSIXs", "ide", "IDE - VS Code", safe, True, "Cached VSIX payloads can be redownloaded."),
        Target("VS Code logs", home / "Library/Application Support/Code/logs", "ide", "IDE - VS Code", review, True, "Logs can be removed but may hide editor issues."),
        Target("VS Code SW cache", home / "Library/Application Support/Code/Service Worker/CacheStorage", "ide", "IDE - VS Code", safe, True, "Service worker cache can be regenerated."),
        Target("Cursor cache", home / "Library/Application Support/Cursor/Cache", "ide", "IDE - Cursor", safe, True, "Editor cache only; do not close editor automatically."),
        Target("Cursor cached data", home / "Library/Application Support/Cursor/CachedData", "ide", "IDE - Cursor", safe, True, "Editor cache only; do not close editor automatically."),
        Target("Cursor logs", home / "Library/Application Support/Cursor/logs", "ide", "IDE - Cursor", review, True, "Logs can be removed but may hide editor issues."),
        Target("Xcode caches", home / "Library/Caches/com.apple.dt.Xcode", "xcode", "macOS Junk", safe, True, "Generated Xcode cache."),
        Target("Spotify cache", home / "Library/Caches/com.spotify.client", "app", "macOS Junk", safe, True, "Streaming cache can be regenerated."),
        Target("Slack cache", home / "Library/Caches/com.tinyspeck.slackmacgap", "app", "macOS Junk", safe, True, "App cache can be regenerated."),
        Target("Teams cache", home / "Library/Caches/com.microsoft.teams", "app", "macOS Junk", safe, True, "App cache can be regenerated."),
        Target("Trash", home / ".Trash", "system", "macOS Junk", review, True, "Trash is destructive to empty; review before cleaning."),
        Target("HuggingFace models cache", home / ".cache/huggingface", "ai", "AI/ML Caches", review, True, "Models may be large and redownloadable."),
        Target("Ollama models", home / ".ollama/models", "ai", "AI/ML Caches", review, True, "Models may be intentionally installed."),
        Target("PyTorch cache", home / ".cache/torch", "ai", "AI/ML Caches", safe, True, "Framework cache can be regenerated."),
    ]


def system_data_targets(home: Path = HOME) -> list[Target]:
    review = "review-required"
    blocked = "never-default-delete"
    return [
        Target("System Data: Library Developer", home / "Library/Developer", "system-data", "System Data Discovery", review, False, "Container for Xcode, simulators, archives, and device support; inspect child paths."),
        Target("System Data: Application Support", home / "Library/Application Support", "system-data", "System Data Discovery", blocked, False, "Mixed app databases, settings, and caches; report only."),
        Target("System Data: Containers", home / "Library/Containers", "system-data", "System Data Discovery", blocked, False, "Sandboxed app data; report only."),
        Target("System Data: Group Containers", home / "Library/Group Containers", "system-data", "System Data Discovery", blocked, False, "Shared app data; report only."),
        Target("System Data: MobileSync backups", home / "Library/Application Support/MobileSync/Backup", "system-data", "System Data Discovery", review, False, "Old iPhone/iPad backups can be large; remove through Apple-supported UI where possible."),
        Target("System Data: private var folders", Path("/private/var/folders"), "system-data", "System Data Discovery", blocked, False, "macOS temp/cache area with protected runtime data; report only."),
        Target("System Data: virtual memory", Path("/private/var/vm"), "system-data", "System Data Discovery", blocked, False, "Swap/sleep files are managed by macOS; restart is safer than deletion."),
        Target("System Data: Docker container data", home / "Library/Containers/com.docker.docker", "system-data", "System Data Discovery", review, False, "Docker can hide images, volumes, and VM disks; use Docker prune with care."),
        Target("System Data: user cache root", home / ".cache", "system-data", "System Data Discovery", review, False, "Mixed tool caches; inspect children before deleting."),
    ]


def target_to_item(target: Target, size: int) -> dict:
    return {
        "name": target.name,
        "path": str(target.path),
        "size": size,
        "size_human": fmt_size(size),
        "category": target.category,
        "group": target.group,
        "safety": target.safety,
        "cleanable": target.cleanable,
        "reason": target.reason,
    }


def scan_targets(targets: list[Target], min_size: int = MIN_SCAN_SIZE, include_zero: bool = False) -> list[dict]:
    items = []
    for target in targets:
        if not target.path.exists():
            continue
        size = dir_size(target.path)
        if size >= min_size or (include_zero and size == 0):
            items.append(target_to_item(target, size))
    return sorted(items, key=lambda item: item["size"], reverse=True)


def scan_known_items(home: Path = HOME, min_size: int = MIN_SCAN_SIZE) -> list[dict]:
    return scan_targets(known_targets(home), min_size=min_size)


def scan_system_data_items(home: Path = HOME, min_size: int = MIN_SYSTEM_DATA_SIZE) -> list[dict]:
    items = scan_targets(system_data_targets(home), min_size=min_size)
    snapshots = list_local_snapshots()
    if snapshots:
        items.insert(0, {
            "name": "System Data: Time Machine local snapshots",
            "path": "/",
            "size": 0,
            "size_human": "unknown",
            "category": "system-data",
            "group": "System Data Discovery",
            "safety": "review-required",
            "cleanable": False,
            "reason": f"{len(snapshots)} local snapshot(s) detected; use Time Machine settings or tmutil after review.",
        })
    return items


def group_items(items: list[dict]) -> dict[str, list[dict]]:
    grouped: dict[str, list[dict]] = {}
    for item in items:
        grouped.setdefault(item["group"], []).append(item)
    return grouped


def list_local_snapshots() -> list[str]:
    try:
        result = subprocess.run(
            ["tmutil", "listlocalsnapshots", "/"],
            capture_output=True,
            text=True,
            timeout=10,
        )
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return []
    if result.returncode != 0:
        return []
    return [line.strip() for line in result.stdout.splitlines() if line.startswith("com.apple.TimeMachine.")]


def clean_scan_item(item: dict) -> int:
    if not item.get("cleanable", False):
        return 0

    path = Path(item["path"])
    if not path.exists():
        return 0
    if is_protected_development_store(path):
        return 0

    try:
        if path.is_dir():
            if path == HOME / "Library/Caches":
                return clean_cache_root(path)
            size = dir_size(path)
            shutil.rmtree(path, ignore_errors=True)
            if "cache" in item["name"].lower() or "Cache" in str(path):
                path.mkdir(parents=True, exist_ok=True)
            return size
        if path.is_file():
            size = path.stat().st_size
            path.unlink()
            return size
    except (PermissionError, OSError):
        return 0
    return 0


def is_protected_development_store(path: Path) -> bool:
    return any(part in PROTECTED_DEVELOPMENT_STORE_DIR_NAMES for part in path.parts)


def clean_cache_root(path: Path) -> int:
    cleaned = 0
    for child in path.iterdir():
        if child.name in PROTECTED_CACHE_DIRS:
            continue
        try:
            if child.is_dir():
                size = dir_size(child)
                shutil.rmtree(child, ignore_errors=True)
                cleaned += size
            elif child.is_file():
                size = child.stat().st_size
                child.unlink()
                cleaned += size
        except (PermissionError, OSError):
            pass
    return cleaned
